### ISSUE TITLE
Using MSE instead of Broadway?

### ISSUE THREAD

**Issue by orcaman** [bkw/node-dronestream#14]
Hi,

Great project, creative and awesome. 

Question: although Broadway is super cool, did you consider using Media Source Extensions to decode the video using the browser's native decoding API? 

I mean, if I am not missing something, eventually you broadcast H264 bytes over Web Sockets to a browser client. If that client supports MSE, we should be able to append the H264 bytes in array buffer form to a MSE buffer, right? At least in theory (if only the NAL units are sent I guess you need to wrap them up somehow but that's pretty much it). 

Thanks!

**Comment by bkw** [comment]
Cool suggestion, and it may be worth looking into this again.

When I experimented with that (a looong time ago), I could not get the video to decode in real time, the browser always insisted on buffering a few seconds - to guarantee smooth playback I guess.
That's what led me to broadway in the first place - the ability to decode a frame as soon as it's available, without worrying much about a coherent move experience.
But things may have changed since then, maybe now we can let the browser decode a NAL unit immediately.

I currently don't have the time to look into this, but as always: pull requests welcome :-)

**Comment by orcaman** [comment]
Got it. Thanks for the feedback. Will be glad to work on a PR when I find some time.
